### ISSUE TITLE
Luna doesn't currently work on Julia 1.8 on m1 Mac

### ISSUE THREAD

**Issue by jtravs** [LupoLab/Luna.jl#287]
See this issue with CoolProp: https://github.com/CoolProp/CoolProp.jl/issues/20

**Comment by chrisbrahms** [comment]
It's specifically Mac OS with v1.8 I think. It runs fine on my windows machine with v1.8 and also in the CI

**Comment by jtravs** [comment]
This is now resolved upstream and seems to work.
