### ISSUE TITLE
Difference in critical power prefactor?

### ISSUE THREAD

**Issue by chrisbrahms** [LupoLab/Luna.jl#297]
In `Tools.jl` we currently have 1.8962 as the prefactor for the critical power:https://github.com/LupoLab/Luna.jl/blob/916f6b2057546ff760168c60e913277e6a79ed3b/src/Tools.jl#L75

This is the "bulk medium" number for a Gaussian beam in Fibich and Gaeta:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/38351086/189334624-afd45465-0f26-4a42-b89e-ba644a5aef19.png">

Should we not be using Ncr (1.86225) instead, since we're talking about propagation in a hollow waveguide?

@jtravs

**Comment by jtravs** [comment]
Yes, I agree. In the end I don't think it makes much difference, because we tend to use extra safety factors anyway, making the small difference here negligible. But it is of course better to be precise.

**Comment by chrisbrahms** [comment]
You're right of course. The only reason I care about this is that my tests on HiSol.jl fail when I compare to the numbers from Luna
