### ISSUE TITLE
DataPulse method needs the sign of the spectral phase to be flipped to work correctly 

### ISSUE THREAD

**Issue by federicocappenberg** [LupoLab/Luna.jl#319]
Dear developers,

from the Luna documentation (A note on sign conventions) I expected positive GDD to be represented by a spectral phase with positive concavity. Istead if I give a pulse as an input to the program through the DataPulse(ω, Iω, ϕω; energy, λ0=NaN, mode=:lowest, polarisation=:linear, propagator=nothing) method, when the  spectral phase concavity is positive and I plot the pulse time profile at the starting position through Plotting.time_1D(output, [0]; trange=(-50e-15, 50e-15)) , I obtain that it is flipped in time with respect to the expected one. This is consistent with a change of sign of the spectral phase after the definition.
Original phase;
![orig_FROG phase](https://user-images.githubusercontent.com/127214234/223438790-141a13fa-ea3f-4b64-8eca-f95ad930a668.png)
Pulse time profile at the starting position:
![orig_FROG time](https://user-images.githubusercontent.com/127214234/223441675-b6affa3e-51e0-4d79-ae46-e9da261b2faf.png)
As time profile should appear:
![orig_FROG time_MATLAB](https://user-images.githubusercontent.com/127214234/223441850-93293c40-ecef-4028-be7b-fc1fac401c83.png)
At this point I ran in any case the simulation and I obtained no RDW (input pulse centered at 800 nm):
![3_bar_72uJ_FROGnegphase_wlfull_4modes](https://user-images.githubusercontent.com/127214234/223442048-6a6be8e3-6fad-461c-9591-c7d7d800b906.png)
Then I tried to change the sign to the spectral phase and with negative concavity I obtained the dynamic of the RDW:
![3_bar_72uJ_FROG_wlfull_4modes](https://user-images.githubusercontent.com/127214234/223442354-909dde6c-fcea-40fe-a282-2316deeff129.png)
From my experience the RDW dynamics should be more likely when the pulse has positive GDD.
I think all these tests suggest that DataPulse considers positive GDD when the concavity of the spectral phase is negative.
Could you please check wheter this is the case, and make the concavity of the spectral phase and the GDD sign consistent with the convention of the documentation, if needed?
Thank you for the attention,
best wishes,

Federico

**Comment by chrisbrahms** [comment]
Hi Federico,

You're correct, a `DataPulse` requires the sign of the phase to conform to the mathematical convention for the Fourier transform rather than the optical convention. Unfortunately this is where the two conventions collide and there is really no way to be completely consistent--is the phase of the field a physical quantity or part of the field?

I'll need to think a bit before changing anything here, because it also interacts with a few other places, but at the very least we should have a note about this in the documentation. Sorry about the confusion!

**Comment by federicocappenberg** [comment]
Thank you very much for the very quick clarification!
