### ISSUE TITLE
Bibliography request regarding multimode treatment

### ISSUE THREAD

**Issue by Jrcarand** [LupoLab/Luna.jl#326]
Hello again and I am sorry for taking your time.

I see in the plotting cases, that when doing multimode capillary sims, that when I would want the sum of all modes, the sum is made in intensity rather than abs2(sum(fields)). In the answer of another issue, you also mention that summing the fields is not meaningful, but the sum of the intensities is.

I tried to follow several publications [1..3], but I still do not understand why is that treatment the valid treatment. From all these sources I see treatment of the full spatio-temporal E field, the treatment of each mode integrated over (r,theta), but not explicit mentions of the treatment of the fully integrated intensity signal at the end of a capillary, eg spectral power density output of all modes. I am used to think about the coherent combination of the modes and the way they interfere with each other. Even if using an orthogonal basis I imagine, within the capillary, spatiotemporal overlap of E-field envelopes and phases.

I see that for the calculation of the nonlinear terms you do calculate the whole spatio-temporal field and later do the projection onto the modes. I also understand that each mode's intensity is simply its abs2(), I am still failing to see how the different HE modes do not interfere with each other when wanting to know the full intensity signal. (Do I understand correctly that the HE_1m modes are just based off of the J_0 Bessel, or basically the LP_0m modes, so with cylindrical symmetry?)

Is it because after projection onto the modes, you already have the integrals of the orthogonal normalization getting rid of the (r,theta) dependence and the E_j(omega) already "counts with the whole interference"? Or in other words, your basis makes my typical mentality of the plane-wave approximation where I treat a full spatio-temporal beam as simply E(omega) incorrect. I have a feeling the reason is somewhere where the (r,theta) dependency is dropped, through the orthonormal treatment of the modes.

Do you have any kind of bibliography where this is explicitly mentioned, or a simple explanation why the treatment follows the integration of the intensities rather than the intensities of the summed E-fields of the different HE modes?

1. Travers, J. C., Grigorova, T. F., Brahms, C. & Belli, F. High-energy pulse self-compression and ultraviolet generation through soliton dynamics in hollow capillary fibres. Nature Photonics 13, 547–554 (2019).
2. Tani, F., Travers, J. C. & Russell, P. S. J. Multimode ultrafast nonlinear optics in optical waveguides: numerical modeling and experiments in kagomé photonic-crystal fiber. J. Opt. Soc. Am. B, JOSAB 31, 311–320 (2014).
3. Kolesik, M. & Moloney, J. V. Nonlinear optical pulse propagation simulation: From Maxwell’s to unidirectional equations. Phys. Rev. E 70, 036604 (2004).

**Comment by chrisbrahms** [comment]
You can see this quite easily by expanding the modes. Say we want to calculate the total instantaneous power in a waveguide. Then we need to integrate over the fibre core (denoted here as S):
<img width="474" alt="image" src="https://github.com/LupoLab/Luna.jl/assets/38351086/cc83675d-ddbb-4e05-86a8-46427dd03fcf">
ehat here are the normalised mode profiles of the waveguide modes, and E_m are the mode amplitudes (this is what Luna propagates and outputs, though in the frequency domain). For the last step you need to use the chosen normalisation of the mode profiles--not by coincidence, Luna normalises the modes such that that integral evaluates to 2/(ε_0*c), cancelling out the prefactor. See https://github.com/LupoLab/Luna.jl/blob/d7273b9433f755a9e083edf159c18ff18d0a006f/src/Modes.jl#L53

Does this help?

**Comment by Jrcarand** [comment]
Ok, I see. So I guess that the reason why the summation passes to the outside of the abs2() is because all cross terms have a dot product between two different orthogonal versors, hence all cross terms drop out. This was the point that was not obvious to me initially, but now I can see why it works.

However, I have a last question regarding eq11 of my ref 2 in the first post (below), derived for the nonlinear response of the first mode of a waveguide.

![image](https://github.com/LupoLab/Luna.jl/assets/77054323/8e3e616c-087e-4bec-acc8-87b227eaba62)

There the ê_j is also function of omega. I had a belief that mode decomposition in this case would be just function of (r,theta). Is there a meaning to that? Wouldn't this mean that each frequency has its own modal decomposition, but for a fiber shouldn't this be fixed? I understand that the initial derivations were for a general case, but for a waveguide I would imagine only (r,theta) dependence.

I cannot express how thankful I am for your fast answers to all my questions! Thank you a lot.

**Comment by chrisbrahms** [comment]
> Ok, I see. So I guess that the reason why the summation passes to the outside of the abs2() is because all cross terms have a dot product between two different orthogonal versors, hence all cross terms drop out. This was the point that was not obvious to me initially, but now I can see why it works.

Yes, you're correct--I actually abbreviated the derivation incorrectly above! Of course the sum only really drops out of the abs2 once you take the transverse integral.

> There the ê_j is also function of omega. I had a belief that mode decomposition in this case would be just function of (r,theta). Is there a meaning to that? Wouldn't this mean that each frequency has its own modal decomposition, but for a fiber shouldn't this be fixed?

In general, the shape of a waveguide mode is not independent of frequency. For most types of waveguides this is actually a huge approximation! Luna currently completely ignores the frequency dependence of the modes and the effective area, because it's true for hollow capillaries and nearly true for other hollow-core fibres, but it has long been on our to-do list to fix this--see for example ancient issue #60

**Comment by Jrcarand** [comment]
All clear!

Thank you so much, I really appreciate it!
